### ISSUE TITLE
Data Week: Create and Maintain a Database Table for Weight Changes in Unique Humanity Scoring Model

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2050]
### User Story:
As a data scientist or administrator of the Gitcoin Passport platform,
I want to have a database table that records all changes made to the scoring model's weights for each credential,
So that I can keep track of historical scoring model configurations and optimize them effectively.

### Acceptance Criteria
GIVEN I am a user with appropriate permissions,
WHEN I access the Gitcoin Passport platform,
THEN I should be able to view and maintain a database table that records the following information for each scoring model configuration change:

1. Date and Time of the change.
2. Unique Identifier for the scoring model configuration change (e.g., a version number or name).
3. Weight assigned to each credential in the scoring model for that specific configuration.
4. Threshold value for determining Unique Humanity.
5. A reference or description field for the reason or context of the configuration change (optional).

#### Product & Design Links:
<links>

#### Open Questions:
- [ ] Maybe we should add the Stamp category the credential falls into?

**Comment by nutrina** [comment]
### Tech notes
1. create a model like `WeightConfiguration` with fields like version, threshold, description, name, active, etc ...
  a. only 1 record can be active at 1 point in time
2. create records within that model `WeightConfigurationItem` that will hold the weight for a single provider
3. consider allowing CSV upload for the list of records in a `WeightConfiguration` object ...
