### ISSUE TITLE
Flag Error if Ceramic Write Failures Exceed 1% of Total Writes for a Time Period

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2568]
### User Story:
As Passport and Ceramic developers
I want to flag an error if Ceramic write failures exceed 1% of total writes over a specific time period (hourly/24 hours),
So that I can quickly identify and address potential issues with data writes.

### Acceptance Criteria
GIVEN the system monitors total write operations to the Ceramic database,
WHEN the failure rate exceeds 1% of total writes within 24 hours,
THEN the system should flag an error and alert the Ceramic, HireNodes & Passport.

#### Tech Details:

- Implement monitoring and logging for write operations to the Ceramic database.
- Calculate the failure rate of writes on an hourly and daily basis.
- Trigger alerts if the failure rate exceeds the 1% threshold.
- Manually set up in Datadog
- Email Alert(s) should be sent to engineering @ Passport (is it setu

#### Open Questions:
- [ ] Setup the engineering @ passport xyz email 

#### Notes/Assumptions:

- The monitoring system is assumed to have access to all write operation logs.
- Alerts are configurable and can be customized based on administrator preferences.

**Comment by nutrina** [comment]
This should be solved via monitoring in Datadog

**Comment by lucianHymer** [comment]
I have the alert set up, but I need to add a couple "info" messages to the passport code (attached PR).

Once that's in production, I'll tweak the alert in Datadog to look for the right thing (should take 10 minutes or less).

**Comment by lucianHymer** [comment]
Blocked on needing an engineering@passport.xyz email group
