### ISSUE TITLE
Data Week: Internal Batch Scoring MBD API Endpoint (Part 1)

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2631]
**User Story:**
As a **data engineer**, I want to **set up an internal batch scoring MBD API endpoint**, so that I can **process large datasets efficiently for the data team and provide results in a downloadable CSV file**.

**Acceptance Criteria:**
GIVEN the internal API endpoint,
WHEN the data team submits a list of addresses with their API key,
THEN the API should provide an estimated processing time and a job ID, allow status checks via a separate endpoint, and return an S3 bucket link to download the CSV file with the results when the job is completed.

**Tech Details:**
- Implement the internal batch scoring API endpoint (or upload a list/csv file from Django Admin)

The rest of the story is covered in[ part 2](#2680 )

**Open Questions:**
- [ ] Are there any specific performance metrics to consider?
- [ ] What specific format should the CSV file follow?

**Notes/Assumptions:**

**Comment by Jeremy-Gitcoin** [comment]
Split the ticket:
(1) - Django admin to upload file - 3 points 
(2) - Infrastructure details for the job to do the analysis. Process all of the data, but only 5 to be done in parallel + Data store (DB) of output and generating the file - 5 points

**Comment by Jeremy-Gitcoin** [comment]
Updated and split the story, part 2 #2680
