### ISSUE TITLE
Data Week: Redash to Superset Migration

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2634]
**User Story:**
As a **data analyst**, I want to **migrate from Redash to Superset**, so that I can **leverage advanced analytics and visualization capabilities**.

**Acceptance Criteria:**
GIVEN the migration setup,
WHEN roles and connections are established,
THEN data team members should be able to access analytics tables and Redshift via Superset.

**Tech Details:**
- Set up Superset.
- Create roles for the data team.
- Establish connections to analytics tables and Redshift.
- (Optional) Set up connection to Datadog.

**Open Questions:**
- [ ] 

**Notes/Assumptions:**
- Assume data team members are familiar with Superset.

**Comment by nutrina** [comment]
Superset has been deployed to review.

Open topics:
- move to secrets manager:
  - SECRET_KEY
  - DATABASE_PASSWORD
- change admin email to something like passport@gitcoin.co
- email configuration (to be able to reset passwords ...)
- no password recovery or reset available atm
