### ISSUE TITLE
Shape L2 Testnet Setup

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#2687]
### User Story:
As as user on Shape L2
I want to prove that I have gone through a KYC (have one of Passport's 4 KYC stamps)
So that I can test utilizing onchain Passport attestations in the L2 environment to unlock benefits

### Acceptance Criteria
GIVEN the developers of Shape L2
WHEN they interact with their addresses
THEN they have onchain Passports and scores to test features of using Passport

**Shape Details**
Testnet: Sepolia (so you can bridge Sepolia eth over and use it on Shape)
Public rpc url: https://sepolia.shape.us/
Chain id: 11011
Initial addresses to attest: 0x70FEEEC90D37dc73D9deD8cfAfd7edE3F697b70B, 0x0F9acF892C809d27d9CD14059aADa68B343d0412

Checklist:
- [ ] Attestor & decoder contracts
- [ ] Attestations made on for the above addresses

#### Product & Design Links:
<links>

#### Open Questions:

- [ ] Is there a way for other addresses to attest and push onchain? (e.g. could we enable this on one of our test environment(s)?

**Comment by Jeremy-Gitcoin** [comment]
Let's attest  "CoinbaseDualVerification" &  "Outdid" to 0x70FEEEC90D37dc73D9deD8cfAfd7edE3F697b70B and
BinanceBABT & HolonymGovIdProvider to 0x0F9acF892C809d27d9CD14059aADa68B343d0412

And if you want to do a few random other credentials to each that's great, but not required.

**Comment by nutrina** [comment]
Blocked by error with the RPC URL.

**Comment by nutrina** [comment]
This has been resolved.
