### ISSUE TITLE
Linea Sepolia testnet deploy / EAS-proxy file update

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#2689]
### User Story:
As a developer building with Linea's verax registry
I want to be able to test an integration on their testnet before integrating
So that I can get early adoption, test the integration, and explore what's possible

---

From Joseph:

Hi - I've run into some blockers on the Verax tutorial. It seems like the passport verax contracts aren't deployed to the Linea Sepolia testnet - the addresses listed in the Gitcoin repo are either wrong or they refer to the Linea Goerli testnet which is now deprecated. This is what I think is going on but it's hard to verify because there's no Linea Goerli explorer anymore and the Gitcoin json object just specifies "Linea testnet" but not which specific testnet. 

Do you know if there's a plan to deploy the contracts to Linea Sepolia?

**Comment by lucianHymer** [comment]
Doesn't look like EAS is deployed here. I'll reach out to see if they plan to release there.

**Comment by lucianHymer** [comment]
We decided not to deploy here
