### ISSUE TITLE
Move Passport Frontend from Fleek to AWS Amplify

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2730]
### User Story:
As a developer,
I want to migrate the Passport frontend from Fleek to AWS Amplify,
So that I can leverage better CI/CD capabilities, enhanced security, and improved scalability.

### Acceptance Criteria
GIVEN the Passport frontend is currently hosted on Fleek,
WHEN the migration to AWS Amplify is completed,
THEN the frontend should be deployed with no downtime, maintain all functionalities, and show performance improvements.

#### Tech Details:

- Infrastructure Setup: Configure AWS Amplify environment, set up IAM roles and policies.
- CI/CD Integration: Link GitHub repository with AWS Amplify, set up automated builds and deployments.
- Environment Configuration: Migrate environment variables and settings from Fleek to AWS Amplify.
- Domain Management: Transition DNS records, set up SSL certificates.
- Testing & Validation: Conduct thorough testing, validate performance improvements.
- Documentation & Training: Update documentation, provide training sessions for the team.

#### Open Questions:

- [ ] Are there any specific security considerations we need to address during the migration?
- [ ] How will the migration impact our current users, if at all?
- [ ] Are there any dependencies or integrations that need to be reconfigured post-migration?

#### Notes/Assumptions:

- No downtime is expected during the transition.
- All team members are familiar with AWS Amplify.
- Performance improvements are a key objective of this migration.

**Comment by digitalmnt** [comment]
Tried various methods and having trouble deploying to amplify. @nutrina mentioned that we is going to take a look at it.

**Comment by digitalmnt** [comment]
Blocked and waiting for login info for: https://docs.google.com/document/d/1DTY5Ve5US5ast0fvF1CjpHsMIlUS5wvJjTUsxYwtY0o/edit

**Comment by nutrina** [comment]
This merge will deploy the passport app on `passport.xyz` for each env. These deployments need testing (oauth setting will need adjustments because of new redirects).
The Fleek version serving on `gitcoin.co`will continue to exist.
