### ISSUE TITLE
Reorient Success Toast on Mobile to Avoid Intercom Misclicks

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2734]
### User Story:
As a user,
I want to easily close the success toast on mobile
So that I can avoid accidentally opening the Intercom widget.

### Acceptance Criteria
GIVEN the success toast notification on a mobile device,
WHEN I attempt to close the notification by clicking the 'X' button,
THEN the 'X' button should be repositioned or the success toast should be relocated to ensure it is not near the Intercom widget, preventing accidental misclicks.

#### Tech Details:

- Investigate current positioning of the success toast and Intercom widget on various mobile devices.
- Propose and implement a new position for the success toast or its close button that ensures a clear distinction from the Intercom widget.
- Ensure that the new positioning maintains usability and visibility of the success toast.

#### Open Questions:

- [ ] Are there specific mobile devices or screen resolutions where this issue is more prevalent?
- [ ] Should we consider a user setting to control the position of the success toast?

#### Notes/Assumptions:

- Assumption that the issue is primarily on mobile devices and not on desktop.
- Consideration of various screen sizes and orientations (portrait and landscape) for mobile devices.

**Comment by nutrina** [comment]
@erichfi  I would move the toast to the top of the screen for small device. Is that acceptable?
