### ISSUE TITLE
Stamp information update: Outdid

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#2744]
We need to update the Stamp description to the following:

[Outdid's free ZK ID verification brings a strong Sybil signal with complete privacy and anonymity.](https://outdid.io/)

To get the Stamp:

Step 1: Click the button below "Get Stamp"
Step 2: Select the country of your identity document and the type of document (eg. Germany, passport)
Step 3: Scan the QR code, download our app and scan your passport.
Step 4: You got your Stamp.

Need help? Message us at t.me/outdidsupport

Outdid is an app which scans the NFC chip of your passport and generates a Zero-Knowledge Proof that you are a unique human. All of your private data stays on your phone - not even Outdid can see it 🙂 Learn more...

=====================

Some notes additional notes and changes:
* Please keep the top linked section as is. 
* Make sure the t.me/outdidsupport is hyperlinked
* Make sure the Learn more... is hyperlinked to https://support.passport.xyz/passport-knowledge-base/stamps/how-do-i-add-passport-stamps/guide-to-add-outdid-stamp-to-passport
* Replace "Name of the Stamp platform group" with "ZK passport"?
* Change the button text from "Verify" to  "Get Stamp"

**Comment by lucianHymer** [comment]
*Change the button text from "Verify" to "Get Stamp"*
This isn't cutomizable, and changes to verifying/verified. We could make it customizable if desired, but it doesn't seem necessary to me

**Comment by lebraat** [comment]
Depending on how much effort this would take....
* If making it customizable is easy, I would say the three states that you outlined will work great!
* If it's less easy, can we make a slight adjustment to the description text to point towards the 'verify' button as opposed to the 'get stamps' button?

---

Separately -- I will take a look through this pull request to better understand where y'all made this adjustment. The one thing I don't have a good grasp on yet is your deploy process, so any guidance around that will help me get across the finish line for being able to make my own Stamp description updates!

**Comment by lucianHymer** [comment]
I'll quickly switch it to _Verify_!

But we actually do have a "connectMessage" parameter that was configured for each platform. It looks like we stopped reading this value when we made the UI updates. We should bring it up with the group if we want to support this in the UI, and if so do an audit of the current values! @erichfi

**Comment by lucianHymer** [comment]
Also @lebraat you usually don't need to worry about the release process unless it's for a hotfix. Generally we just open PRs, pair or review with at least one other person, and merge to main. Then do a weekly release usually on Tuesday!

**Comment by lebraat** [comment]
Thank you! 

Wrote up a quick runbook here: https://docs.google.com/document/d/1ueLfywCe5EG8j8qjUpclhtBc8oJC1ArxH9e2d2KUfuo/edit

**Comment by lebraat** [comment]
> But we actually do have a "connectMessage" parameter that was configured for each platform. It looks like we stopped reading this value when we made the UI updates. We should bring it up with the group if we want to support this in the UI, and if so do an audit of the current values! @erichfi

Not a super high priority, but I do believe this is a worthwhile customization for Stamp partners.
