### ISSUE TITLE
Passport app shows content for previously connected wallet

### ISSUE THREAD

**Issue by nutrina** [passportxyz/passport#2750]
Steps to reproduce:

Make sure you have 2 wallets in Metamask, each with a different set of credentials
1. Connect to Passport using Wallet A
2. The stamps for Wallet A are displayed
3. switch the connected wallet from Metamask to Wallet B
4. The Passport app will take you back to the login / connect screen
5. Connect to the Passport App
6. **Problem:** the widget on the top right shows Wallet B, but Passport still displays the stamps for Wallet A

**Comment by lucianHymer** [comment]
I can't finish #2780 without doing this
