### ISSUE TITLE
Custom Dashboard Integration

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2760]
### User Story:
As a user of the Passport app,
I want the custom campaign banner to be prominently displayed on the mobile version,
So that I can easily access the latest campaigns and features.

### Acceptance Criteria
GIVEN the user is viewing the custom dashboard on a mobile device,
WHEN the dashboard is displayed,
THEN ensure the custom campaign banner is at the top as per the new design.

#### Product & Design Links:
[Figma Design File
](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=3761-36672&t=Z0FffbHBeb2wvYV3-0)
#### Tech Details:
Ensure the custom campaign banner is positioned at the top in the mobile view.

**Comment by lucianHymer** [comment]
Addressed in https://github.com/passportxyz/passport/issues/2757
