### ISSUE TITLE
Update CTA for Users with Onchain Passport

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2763]
### User Story:
As a user of the Passport app,
I want the CTA button to reflect the status of my onchain passport,
So that I see relevant actions based on my score and passport status.

### Acceptance Criteria
GIVEN the user's score is above 20,
AND the user has an up-to-date onchain passport,
WHEN the user sees the CTA button,
THEN the button should say "See Onchain Passports" instead of "Mint Onchain Passport."

#### Product & Design Links:
[Figma Design File
](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=3761-36672&t=Z0FffbHBeb2wvYV3-0)
#### Tech Details:

- Implement logic to check the user's score and the status of their onchain passport.
- Update the CTA button text to "See Onchain Passport" when the user's score is above 20 and they have an up-to-date onchain passport.
- Ensure the button retains its functionality and leads to the appropriate page or action.

**Comment by tim-schultz** [comment]
Waiting on clarification: https://discord.com/channels/562828676480237578/1103046474624933939/1277747008827818025

**Comment by tim-schultz** [comment]
@erichfi @lebraat We are waiting on the link for `Here's what you can do with your passport!` Daniel said he should have it ready in the next week or so
