### ISSUE TITLE
[BUG]  Passport Dashboard is showing wallet balance 

### ISSUE THREAD

**Issue by YukiPL** [passportxyz/passport#2771]
**Overview**
Passport Dashboard is showing wallet balance on the top right corner. The amount is not accurate. 

**Observed  behavior**
![image](https://github.com/user-attachments/assets/c6b7c374-8004-45e1-b672-5164ec004c0e)
![image](https://github.com/user-attachments/assets/dede0023-e161-4477-8716-ef0d03fe7863)

**Expected behavior**
The Wallet balance should not be showing.

**Additional context**
User is using Chrome.

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/81988?view=List

**Comment by hellenDevs** [comment]
@YukiPL Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Moderator0xa** [comment]
@YukiPL Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by lucianHymer** [comment]
@erichfi Do we want to hide the wallet balance in all cases? We can do that. But as far as the incorrect amount here, it's probably either

1) The user is connected to a weird testnet chain where they do have these funds
2) The user's network setup in Metamask is wrong
3) A bug in web3modal
