### ISSUE TITLE
Warning Modal for Low Score Onchain Passport Minting

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2777]
### User Story:
As a Passport user,
I want to be warned when attempting to mint an onchain passport with a low score,
So that I can make an informed decision and understand the implications of minting with a low score.

### Acceptance Criteria
GIVEN the user has a passport score below 20,
WHEN the user attempts to mint their passport onchain,
THEN a warning modal should appear, informing the user that minting with a low score may provide limited benefits and perks, but most integrations require a minimum score of 20. Additionally, the modal should note that minting will incur a cost of approximately ETH worth $3.

The warning modal should work consistently across both the default dashboard and any custom dashboards.

The warning modal should contain the following updated copy:

**Title:**
"Low Score Warning: Are You Sure?"

**Body:**
"Your current passport score is below 20. While some benefits might be available with a lower score, most integrations require a score of 20 or higher to unlock full benefits and perks. This action will cost approximately ETH worth $3. Do you still wish to proceed?"

**Buttons:**
- Confirm button: "Proceed with Minting"
- Cancel button: "Cancel"

#### Product & Design Links:
[Design Mockup
](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=12154-4475&t=sWyteemNV9Bh4VLJ-1)

#### Tech Details:

- Implement the modal with the updated copy and buttons.
- Ensure the modal triggers only if the user's score is below 20.
- The implementation should ensure that the warning modal is compatible with both the default dashboard and any custom dashboards, maintaining consistent behavior and appearance.

#### Open Questions:

- [ ] Should the user be prompted again if they dismiss the warning and attempt to mint within the same session?

#### Notes/Assumptions:
- The score check is a critical part of this feature and must be in sync with the latest user data.

**Comment by lebraat** [comment]
2 things...
1. Are we going to be able to track the different actions within this modal? It'd be interesting to see how many people dismiss the modal and don't proceed with minting onchain. If this eats into our revenue too much, we might want to remove it. 
2. I've included a recommended update to the text below:

-------

Title:
"Try building up a higher score?"

Body:
"While some benefits might be available with a lower score, many partners require a score of 20 or higher.

Do you still wish to proceed?"

**Comment by lucianHymer** [comment]
> 2 things...
> 
>     1. Are we going to be able to track the different actions within this modal? It'd be interesting to see how many people dismiss the modal and don't proceed with minting onchain. If this eats into our revenue too much, we might want to remove it.
> 
>     2. I've included a recommended update to the text below:
> 
> 
> Title: "Try building up a higher score?"
> 
> Body: "While some benefits might be available with a lower score, many partners require a score of 20 or higher.
> 
> Do you still wish to proceed?"

@lebraat Good idea! I'll add a datadog log so that we can pull this metric whenever we want

**Comment by lebraat** [comment]
Thank you, ser!
