### ISSUE TITLE
Authenticate users in intercom chat bot

### ISSUE THREAD

**Issue by jesuloluwao** [passportxyz/passport#2780]
### User Story:
As an admin in intercom
I want to automatically authenticate users when they create requests on intercom
So that they can have a history log of conversations they have open with us and don't lose the conversation midway.

We have many cases where the user reaches out to us but then go offline. When we respond to those users, we don't get a response. I believe they're not receiving our messages anymore because they've lost their session on intercom. Because we don't authenticate users today, users only receive an Intercom cookie to remember their conversation history so when they clear their cookies, change devices or browsers, they will lose their previous conversation history.

If we can authenticate user through their wallet address when they connect, we can retain these conversations and have reduced cases of abandoned chats.

You can find more information on how to do that here https://www.intercom.com/help/en/articles/168-install-intercom-for-users-on-web

#### Product & Design Links:
<links>

**Comment by lucianHymer** [comment]
We don't have access to Intercom, which makes stuff like this harder. Can we (temporarily?) get access to intercom for this?

**Comment by jesuloluwao** [comment]
Hey @lucianHymer is there an engineering email I can share access with, or should I just share with you directly
