### ISSUE TITLE
Display Custom GitHub Stamp and Criteria on Dashboard - Frontend Updates

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2786]
### User Story:
As a Visitor to a custom dashboard,
I want to see the custom GitHub verification stamp and understand the criteria before attempting to claim it,
So that I can decide whether to proceed with the verification process.

### Acceptance Criteria
GIVEN a visitor enters a custom dashboard,
WHEN they view the dashboard,
THEN the custom GitHub stamp should be prominently displayed, along with a clear explanation of the verification criteria (e.g., repository contributions or organization membership).

#### Product & Design Links:
TBD
#### Tech Details:

- The stamp and its criteria must be displayed on the dashboard overview page.
- Ensure the explanation of criteria is clear and concise, based on design specifications.
- the handling for the custom gitub stamp differs from the allowlist stamp in the following ways:
  - the card is always visible on the dashboard regardless if the user verified the stamp or not (the allowlist stamps is only displayed if the user verified it successfully)
  - the verification in this case is always manual (user triggers the verification process manually)

#### Open Questions:
N/A

#### Notes/Assumptions:
N/A

**Comment by nutrina** [comment]
Figma designs: https://discord.com/channels/1201910237238399006/1218698890208088065/1281631904776589354
