### ISSUE TITLE
Implement Basic Slashing Analysis for EOA-Funded Wallets

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2788]
### User Story:
As a Passport system administrator,
I want to implement an analysis of wallets funded by the same EOA,
So that I can identify potential slashing cases without taking action.

### Acceptance Criteria
GIVEN a dataset of staker wallets,
WHEN the analysis runs,
THEN it should identify wallets funded by the same EOA and log these occurrences for further review.

GIVEN the list of identified wallets,
WHEN the data analysis is complete,
THEN it should produce a report accessible to the data and product teams.

#### Product & Design Links:
<links>

#### Tech Details:

- Implement a cron job to regularly run the analysis.
- The frequency of the job should be configurable, with a suggested default of weekly runs once fully deployed.
- Use Redshift for data extraction 

#### Open Questions:

- [x] Should we allow flexibility in the frequency of the cron job, or should it be fixed?
- [x] Would the data team prefer to start with a smaller subset of data for initial testing?

**Comment by nutrina** [comment]
@erichfi This sounds like a topic for the data team, or are we misunderstanding the requirement here?

**Comment by lucianHymer** [comment]
The criteria is that if at least 2 active stakers have the same first funder, they will be slashed. They will continue to be slashed as long as they are both stakers.

**Comment by nutrina** [comment]
@erichfi I think we agreed to get an initial implementation from the data team. Do we already have that?

**Comment by stefi-says** [comment]
@nutrina I have uploded the script in here:  [notebooks/automations/addapting the slashing pipeline](https://github.com/passportxyz/Passport-Data-Science/tree/1563f240ff8ce981ee00b59b38d2655729e68e37/notebooks/automations/addapting%20the%20slashing%20pipeline)
I made some comments on the parts I think you may need to addapt , for example Im using local files to store the first funder  information as well as the entities informations and Im pulling the data from users withh acive stakes from Redash.

**Comment by stefi-says** [comment]
Done! Please double check and let me know if there is any doubt about it

**Comment by nutrina** [comment]
@erichfi  how should this analysis run?

Shall we run it:

1.. on demand?
2. on a schedule?
