### ISSUE TITLE
Migrate PagerDuty to Passport owned account

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#2798]
We need to migrate from the shared PagerDuty account with Grants Labs to a new Passport dedicated account.

I'm not sure what's involved in doing this work?

- [X] create the new PD account
- [x] set up teams and schedules, billing
- [x] create the integrations (uptime robot, datadog, aws, ceramic cache)
- [ ] coordinate with the Ceramic team on the Ceramic node specifications
- [x] update configuration for the infra
- [ ] with the next release the alarms should be sent to the new PD account

**Comment by lucianHymer** [comment]
Don't have permission in PagerDuty

**Comment by lucianHymer** [comment]
Need to follow up about Ceramic tasks
