### ISSUE TITLE
Integration of Passport with Shape Network Mainnet

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2820]
### User Story:
As a Passport holder,
I want to push my Passport to the Shape Network's mainnet,
So that I can participate in Shape Network campaigns and interactions on the mainnet.

### Acceptance Criteria
GIVEN I am a Passport holder,
WHEN I choose the Shape Network mainnet from the list of available chains in the integration options,
THEN I should be able to successfully push my Passport to the Shape Network's mainnet and receive confirmation of the action.

#### Product & Design Links:
N/A

#### Tech Details:

- Ensure the Shape Network mainnet is listed as an option in the network selection.
- Confirm the ability to push Passports to the mainnet environment and verify the transaction.
- **Important:** The EAS protocol is already live on Shape's mainnet, but there is currently no explorer available to link to the attestations. For now, omit linking to attestations in the explorer for Shape Network, unlike other supported chains.

#### Open Questions:

- [ ] What is the timeline for the availability of an explorer on Shape Network to view attestations?

#### Notes/Assumptions:
- Please reach out to @lebraat for details about the Shape Network endpoints, as access is currently limited to developers.
- Context: https://shape.network/

**Comment by nutrina** [comment]
Contracts have been deployed.
This is currently blocked on some UI issues (see Discord thread).

**Comment by nutrina** [comment]
Waiting for review
