### ISSUE TITLE
Investigate missing permissions & error messages for the Data team

### ISSUE THREAD

**Issue by nutrina** [passportxyz/passport#2843]
The following goals are currently not possible due to errors or permission issues:

1. start / stop redshift on a schedule
2. connect AWS Glue to Dynamo DB. This does not work directly, needs to go through S3.
3. Opening security between RedShift & DeepNote to enable connection to run daily jobs

**Comment by larisa17** [comment]
- [x] Redshift scheduler permission done 
- [x] Redshift - Deepnote connection done
