### ISSUE TITLE
Remove center component for custom dashboards

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#2847]
### User Story:
As a partner with a custom dashboard
I want to remove the center component 
So that I can can control the user experience and branding

### Acceptance Criteria
GIVEN a user comes to a custom dashboard /#/<partner>/dashboard
WHEN they get to the main application screen
THEN the center component (push onchain, congrats it's onchain) does not show up

- [x] Show or remove the middle component(s) on each option
- [ ] Override the text on all of the middle component options 1) low score 2) high score / mint on chain [scorer panel text updates, but for both of the 2 versions of the component] 3) High score + minted onchain (see onchain)
- [x] New design(s) for the missing panel should be the same as the left version of [responsiveness](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=3761-36672&node-type=canvas&t=DCngjZ6PWGCjPbZc-0) replacing the score related info section with the partner section [1/3 & 2/3 partner] on the largest screen

**Comment by tim-schultz** [comment]
There is a current override for the following AC:

> Override the text on all of the middle component options 1) low score 2) high score / mint on chain [scorer panel text updates, but for both of the 2 versions of the component] 3) High score + minted onchain (see onchain)
