### ISSUE TITLE
Generic Custom Stamp Implementation

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#2848]
### User Story:
As a ...
I want to ...
So that I can ...

### Acceptance Criteria
GIVEN we have the need for a custom stamp
WHEN we go to implement
THEN we have a clear path on how to implement

We'll use this for the custom Github / new developer list stamp and then it'll make it much easier the next time we want to implement a new custom stamp. 

- [ ] Model for the custom stamp rulesets
- [ ] Model to link a ruleset to a custom dashboard
- [ ] API for the ruleset(s)

#### Product & Design Links:
<links>

**Comment by lucianHymer** [comment]
Keeping this open because I'm 99% sure I'll need to make some small changes that I'll figure out as I work on the frontend
