### ISSUE TITLE
MDB Api Error handling

### ISSUE THREAD

**Issue by nutrina** [passportxyz/passport#2849]
Review & improve error handling in the MDB API

The expected behaviour is that of an error is encountered while processing a request from a user we should return a 500 code with a clean error message.

Right now, the behaviour apparently is that we return a "504 Service down error"

Possible errors:
- alchemy API request times out
- bad API key
- any other error on alchemy end

Also we should document the errors thrown in different scenarios, and what we recommend for each.

### Acceptance Criteria

GIVEN I am in the Passport App
WHEN I try to retrieve any stamp related to an MDB modal
AND and computing the score failed (for example the alchemy API threw an error)
THEN I expect an error message telling me that determining the score failed
AND I that I should try again in a few minutes

GIVEN I am making an API request for a non-aggregate model score ( http://127.0.0.1:8002/passport/analysis/0x4A13F4394cF05a52128BdA527664429D5376C67f?model_list=ethereum_activity )
WHEN the alchemy request fails
THEN I expect an 500 error to be returned with a descriptive error message

GIVEN I am making an API request for an aggregate model score ( http://127.0.0.1:8002/passport/analysis/0x4A13F4394cF05a52128BdA527664429D5376C67f?model_list=aggregate )
WHEN any of the alchemy requests to get the individual model scores fail
THEN I expect an 500 error to be returned with a descriptive error message explaining what failed (which model failed)

### Tested Scenario - bad alchemy API key
I have configured an invalid alchemy API key

#### Request:
```bash
curl -X 'GET' \
  'http://127.0.0.1:8002/passport/analysis/0x4A13F4394cF05a52128BdA527664429D5376C67f?model_list=ethereum_activity' \
  -H 'accept: application/json' \
  -H 'X-API-Key: XXXX'
```

#### Actual
Response 200 with body:
```json
{
  "address": "0x4A13F4394cF05a52128BdA527664429D5376C67f",
  "details": {
    "models": {
      "ethereum_activity": {
        "score": 0
      }
    }
  }
}
``` 

#### Expected
Response 500 with body similar to:
```json
{
  "error": "Failed to retrieve the address history"
}
```

The problem seems to be the exception caught here is not handled and propagated to the API caller: https://github.com/passportxyz/Passport-Data-Science/blob/main/models/eth_stamp_model_v2/src/data/query_eth_node.py#L236-L238

**Comment by tim-schultz** [comment]
[Here](https://us-west-2.signin.aws.amazon.com/oauth?response_type=code&client_id=arn%3Aaws%3Aiam%3A%3A015428540659%3Auser%2Fcloudwatch&redirect_uri=https%3A%2F%2Fus-west-2.console.aws.amazon.com%2Fcloudwatch%2Fhome%3Fregion%3Dus-west-2%26state%3DhashArgs%2523logsV2%253Alogs-insights%25243FqueryDetail%25243D~%2528end~%25272024-09-05T17%252A3a55%252A3a35.675Z~start~%25272024-09-05T17%252A3a10%252A3a11.351Z~timeType~%2527ABSOLUTE~tz~%2527UTC~editorString~%2527fields%252A20%252A40timestamp%252A2c%252A20%252A40message%252A2c%252A20%252A40log%252A0a%252A7c%252A20filter%252A20%252A40message%252A20like%252A20%252A2ferror%252A2f%252A20and%252A20%252A40message%252A20not%252A20like%252A20%252A2fWARNING%252A3a%252A2f%252A20and%252A20%252A40message%252A20not%252A20like%252A20%252A2fItem%252A20size%252A20has%252A20exceeded%252A20the%252A20maximum%252A20allowed%252A20size%252A2f~queryId~%25271e3f94e6-b7ca-499d-8ae6-6e24520b72d8~source~%2528~%2527%252A2faws%252A2flambda%252A2feth-stamp-v2-api~%2527%252A2faws%252A2flambda%252A2faggregate-model-api~%2527%252A2faws%252A2flambda%252A2farbitrum-model-api~%2527%252A2faws%252A2flambda%252A2foptimism-model-api~%2527%252A2faws%252A2flambda%252A2fpolygon-model-api~%2527%252A2faws%252A2flambda%252A2fzksync-model-v2-api~%2527%252A2faws%252A2flambda%252A2fnft-model-api%2529%2529%26isauthcode%3Dtrue&forceMobileLayout=0&forceMobileApp=0&code_challenge=V38gh7PSEQMi0Vj3ngUTU5XggNIoJ6nL7CHbCVlq2gc&code_challenge_method=SHA-256) is a link to a cloudwatch query for errors that are being thrown from within the lambdas during batch execution and normal usage.

**Comment by nutrina** [comment]
@NadjibBenlaldj  I have proposed some changes in the linked PR
We need this in order to be able to raise an error to the user if getting data from Alchemy fails.

Can you please check this?
I think these changes might interfere also with the training process.
