### ISSUE TITLE
Spike: Evaluate using AWS manage solution for running an Eth node

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#2860]
### User Story:
As the Passport team,
I want to have unlimited and cost-effective access to Ethereum transaction data,
So that we can efficiently run analyses and query the blockchain without incurring high third-party costs.

### Acceptance Criteria

GIVEN the need for detailed blockchain data analysis,
WHEN evaluating different options for hosting an Ethereum archive node,
THEN we should decide on the most cost-effective and efficient setup for Passport.

Spike: We'll spend up to 2 days exploring and evaluating if AWS managed services is a feasible alternative

**Exploration Goals**

1. **Evaluate Feasibility:** Explore running an Ethereum a node using [AWS managed solution(s)](https://aws.amazon.com/managed-blockchain/)
2. **Cost Analysis:** Determine the monthly operating cost for both options: a) hosting our own node or b) just quering directly
3. **Decision Making:** Provide a go/no-go recommendation based on findings.
4. **Next Steps:** Outline subsequent stories and tasks if the decision is to proceed with running our own node.

Questions
- [ ] How much to host our own node?
- [ ] What is the cost to query?
- [ ] Can this easily replace the data we're getting from Alchemy?
- [ ] Does this scale to multiple chains (ARB, OP, Polygon, etc)

#### Tech Details:

https://aws.amazon.com/managed-blockchain/ 
https://aws.amazon.com/managed-blockchain/pricing/?nc=sn&loc=3

**Comment by tim-schultz** [comment]
Although [this](https://github.com/passportxyz/passport/issues/2793) ticket doesn't detail the aws hosted solution, it does have an estimate for running nodes using AWS on demand comput

**Comment by lucianHymer** [comment]
Tim's ticket above shows all the info about more manually running our own node(s) in AWS.

Here's the info for the AMB (AWS Managed Blockchain) products

## AMB Query
Only works for Ethereum and potentially Polygon. This gives us a small set of operations we can perform to pull some blockchain data.

For example, the [ListTransactions](https://docs.aws.amazon.com/managed-blockchain/latest/AMBQ-APIReference/API_ListTransactions.html) and [GetTransaction](https://docs.aws.amazon.com/managed-blockchain/latest/AMBQ-APIReference/API_GetTransaction.html) queries.

In alchemy, for each address we call getAssetTransfers twice, and then getTransactionReciept once for each asset transfer transaction (up to 2k). We also call getTokenBalances and getBalance once each to get their ERC20 and Eth balances. This costs up to $0.0114 total per address.

The analogous operations in AMB would be:

- 1 x ListTokenBalances ($7 / million)
- 5 x ListFilteredTransactionEvents ($25 / million)
    - Once for each relevant eventType
    - Seems to only allow filtering by the recipient address, which is only half the data we need 
- 2000 x GetTransaction ($7 / million)

A total cost of $0.0141 per address. Which is ~25% more expensive than Alchemy for less info.


## AMB Access Ethereum
This is the option to just run a node in AWS.

This semi-managed solution is pretty much the same price as [previously estimated](https://github.com/passportxyz/passport/issues/2793) for running a node in AWS, except only for Ethereum. Looks like it would be ~$1400-1600 / month.

Only Ethereum is supported using this solution.
