### ISSUE TITLE
Audit entire app -- Capitalize all instances of 'Passport' and 'Stamp'

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#2881]
I've found a few instances of us not capitalizing Passport and Stamp throughout the app.

Specifically, the new 'mint your passport onchain' module, the "xx days until stamps expire", and I'm sure a handful of other locations.

**Comment by nutrina** [comment]
@lebraat just want to double check, the correct spelling would be:

Specifically, the new 'mint your PASSPORT onchain' module, the "xx days until STAMPS expire", and I'm sure a handful of other locations.

?

**Comment by lebraat** [comment]
Great callout -- We should move forward with B

**Comment by nutrina** [comment]
@lebraat  let's pair on this 15 min today

**Comment by nutrina** [comment]
@lebraat I have deployed another set of fixes to review, they should be live in about ~15 min
