### ISSUE TITLE
Landing Page for Developer Badges

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2896]
### User Story:
As a user in the HR process,
I want to visit a Passport-hosted URL and connect my wallet,
So that I can start the verification process to collect developer badges.

### Acceptance Criteria
GIVEN a user visits the landing page,
WHEN the user sees the connect wallet splash page,
THEN the user can click the `Connect` button to connect their wallet
AND the user is then prompted to sign a message for the Ceramic session in Metamask.

#### Product & Design Links:
- [Link to design](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=15089-12972&node-type=frame&t=GebN12LUWfXFKxpf-0)
- [Link to 1 pager functionality](https://docs.google.com/document/d/1XSX3Lr4s6CvIxiaBsa8-lgrndWG46u0IQXdn6lCC0us/edit?usp=sharing)

#### Tech Details:
- Implement white-label customizable landing page design.
- Use scalable unique URLs for partners.
- Integrate Google Analytics for metrics.
- Host on a specific subdomain (e.g., app.passport.xyz/#/campaign/scroll-developer).
- Connect wallet and create a Ceramic session.
- Obtain the authentication token to our backend.
- Ensure the landing page is accessible on a new domain.

#### Open Questions:
- [ ] Will users expect to see these badges within the Passport app?
- [ ] How might we prevent confusion if badges differ from Stamps?

#### Notes/Assumptions:
- Cannot use www.passport.xyz as the marketing app is on the main domain.
- In the delivered state, we should be able to:
  - Start reading and writing from our API.
  - Make authenticated calls to the IAM.

**Comment by tim-schultz** [comment]
On chain VC verification example: https://github.com/tim-schultz/passport-vc-verification/tree/main

**Comment by nutrina** [comment]
- connect wallet 
- connect with ceramic / create ceramic session
- get the authentication token to our backend
