### ISSUE TITLE
Github Account Integration

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2897]
### User Story:
As a developer,
I want to connect my Github account after connecting my wallet and Ceramic,
So that my credentials can be verified against badge requirements.

### Acceptance Criteria
GIVEN a user has connected to the dapp (this implies wallet + Ceramic connection),
WHEN the user connects their Github account,
THEN their credentials are verified against predetermined badge requirements **(which means checking the number of configured commits)**

#### Product & Design Links:
- [Link to design](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=15089-12972&node-type=frame&t=GebN12LUWfXFKxpf-0)
- [Link to 1 pager functionality](https://docs.google.com/document/d/1XSX3Lr4s6CvIxiaBsa8-lgrndWG46u0IQXdn6lCC0us/edit?usp=sharing)

#### Tech Details:
- also update the provider to check for the number of commits only
- Implement the design and handle the custom domain.
- Deploy the app to the custom domain.
- Set up a new Github OAuth app for the new custom domain.
- Update IAM to support multiple Github OAuth apps (this might require changing the payload sent to IAM in order to be able to identify which Github client ID was used in the app).

#### Open Questions:
- N/A

#### Notes/Assumptions:
- N/A

**Comment by nutrina** [comment]
- design + handle custom domain
- design of the page which says sign in with github

**Comment by nutrina** [comment]
@erichfi  do we want to display the github page in a popup or in the same browser window?
