### ISSUE TITLE
Badge Verification and User Feedback

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2898]
### User Story:
As a developer,
I want to see verification results,
So that I know if I qualify for badges or not.

### Acceptance Criteria
GIVEN the Github account is connected,
WHEN the user's credentials are verified,
THEN the user sees a list of verified badges or a "We're sorry" page if not qualified.

#### Product & Design Links:
- [Link to design](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=15089-12972&node-type=frame&t=GebN12LUWfXFKxpf-0)
- [Link to 1 pager functionality](https://docs.google.com/document/d/1XSX3Lr4s6CvIxiaBsa8-lgrndWG46u0IQXdn6lCC0us/edit?usp=sharing)

#### Tech Details:
- Implement badge verification logic.

#### Open Questions:
- N/A

#### Notes/Assumptions:
- N/A

**Comment by nutrina** [comment]
- depends on what conditions we need to verify that we don't support that
- if no additional verifications are necessary, we'll only need to add support for the new custom domain (which means the github provider needs to support multiple client IDs & secrets)
