### ISSUE TITLE
Onchain Attestation and Badge Minting

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2899]
### User Story:
As a qualified developer,
I want to mint my badges onchain,
So that my credentials are recorded on the blockchain.

### Acceptance Criteria
GIVEN a user is qualified,
WHEN the user clicks the mint button,
THEN an onchain attestation and badge are minted, and a success message with the next step in the Scroll hiring process is shown.

#### Product & Design Links:
- [Link to design](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=15089-12972&node-type=frame&t=GebN12LUWfXFKxpf-0)
- [Link to 1 pager functionality](https://docs.google.com/document/d/1XSX3Lr4s6CvIxiaBsa8-lgrndWG46u0IQXdn6lCC0us/edit?usp=sharing)

#### Tech Details:
- Implement new badge contract and attestor proxy contract.
- Implement a new onchain attestation contract if necessary.
- Ensure single transaction for attestation and badge minting.
- Adjust issuance fees as needed.
- Support from Scroll team for testnet functionality.

#### Open Questions:
- [ ] Will the stamps be stored in the user's Passport in DB or in Ceramic?

#### Notes/Assumptions:
- Potentially charge less for attestations (e.g., $1).

**Comment by nutrina** [comment]
- we need a spike for this which should be on the top of the backlog
