### ISSUE TITLE
Returning User Flow

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2900]
### User Story:
As a returning user,
I want to see the badges I've already obtained,
So that I know my current status and next steps.

### Acceptance Criteria
GIVEN a user revisits the page,
WHEN the user has previously obtained badges,
THEN these badges and the next step in the Scroll hiring process are displayed.

#### Product & Design Links:
- [Link to design](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=15089-12972&node-type=frame&t=GebN12LUWfXFKxpf-0)
- [Link to 1 pager functionality](https://docs.google.com/document/d/1XSX3Lr4s6CvIxiaBsa8-lgrndWG46u0IQXdn6lCC0us/edit?usp=sharing)

#### Tech Details:
- Implement logic to display previously obtained badges.
- Implement logic to show the Scroll hiring process next steps.

#### Open Questions:
- N/A

#### Notes/Assumptions:
- If the user hasn't obtained badges yet, start the flow from the beginning.

**Comment by nutrina** [comment]
- we need some example and more precise spec

**Comment by larisa17** [comment]
Moved it into blocked until the Mint page is completed to be able to test it
