### ISSUE TITLE
Spike: Mint Scroll Canvas Badges from Frontend

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2908]
### User Story:
As an engineer,
I want to investigate if we can mint Scroll Canvas badges from our frontend,
So that we can ensure the minting flow works correctly before full implementation.

### Acceptance Criteria
GIVEN I have one or more valid VCs,
WHEN I call the mintBadge() function of the ScrollDevVerifier smart contract with the list of my VCs,
THEN the corresponding Scroll badges are minted.

GIVEN I have one or more valid VCs,
WHEN I call the mintBadge() function of the ScrollDevVerifier smart contract with one or more VCs,
AND at least one VC is not valid for this use case (either bad signature, bad payload, provider, etc.),
THEN no badge shall be minted,
AND the transaction should be reverted with a proper error.

#### Product & Design Links:
- [Link to design](https://www.figma.com/design/SFzb234NWo6ViBrMD7SWTj/Passport-App?node-id=15089-12972&node-type=frame&t=GebN12LUWfXFKxpf-0)
- [Link to 1 pager functionality](https://docs.google.com/document/d/1XSX3Lr4s6CvIxiaBsa8-lgrndWG46u0IQXdn6lCC0us/edit?usp=sharing)

#### Tech Details:
- Explore integration with Scroll's test network for minting badges.
- Implement a temporary frontend UI to initiate the minting process.
- Ensure smart contract interactions are handled correctly from the frontend.
- Validate if a single transaction can handle both attestation and badge minting.
- Determine if existing contracts or new contracts need to be deployed.
- Validate the VC requires performing validation of the EIP-712 signature of the VC (contact: Tim Schultz).

#### Open Questions:
- [ ] Do we need additional support from the Scroll team for this spike?
- [ ] Are there specific requirements or limitations set by Scroll for minting badges on their test network?

#### Notes/Assumptions:
- Make sure to provide a readme with clear instructions on how to deploy / setup & call the smart contract
- This spike is exploratory and may reveal unforeseen challenges.
- Timebox this spike to one day.
- Collaboration with the Scroll team might be necessary to validate the flow.
- The names mentioned in the acceptance criteria are suggestions and can be modified as necessary.

**Comment by lucianHymer** [comment]
https://docs.google.com/document/d/1wqzmS-kcipCSE9EI15FHRsrA1XuDaRmGHsGm7uJ7oW0
