### ISSUE TITLE
Shape Custom Dashboard Users

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2911]

**Comment by nutrina** [comment]
For the smart contract changes:
- we need to track the default `scorer_id` in the resolver smart contract
- create a new nested map, for example `mapping(address => mapping(uint256 => CachedScore)) public customScorer; // or communityScores`
- writing:
  - we will write all new scores for the default scorer in the old map, named `scores`
  - all other scores we will write to `customScorer`
- add another getter to both the Resolver and Decoder contracts: `getCachedCustomScore(...)` respectively `getCustomScore(...)`
