### ISSUE TITLE
Migrate Django Admin to New Domain

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2914]
### User Story:
As an internal team member,
I want the Django Admin interface to be accessible on the new domain (api.scorer.passport.xyz/admin),
So that I can ensure consistency with our updated domain strategy and streamline administrative processes.

### Acceptance Criteria
GIVEN the Django Admin interface needs to be migrated,
WHEN I navigate to scorer.gitcoin.co/admin,
THEN I should be redirected to api.scorer.passport.xyz/admin.

GIVEN team members need access to Django Admin,
WHEN I attempt to sign in using my Google email,
THEN I should be able to authenticate successfully on the new domain.

#### Product & Design Links:
<links>

#### Tech Details:

- Update DNS to point api.scorer.passport.xyz to the new Django Admin interface.
- Configure Django settings to accept the new domain.
- Ensure SSL/TLS certificates are updated for secure access.
- Implement redirect from scorer.gitcoin.co/admin to api.scorer.passport.xyz/admin.
- Ensure Google OAuth configurations are updated for the new domain.

#### Open Questions:
N/A

#### Notes/Assumptions:

- Migration should not affect other services running on scorer.gitcoin.co.
- Internal team members' access should remain uninterrupted during the migration process.

**Comment by nutrina** [comment]
Option 1: 
api.passport.xyz -> api.production.passport.xyz 

Option 2: 
api.passport.xyz -> ALB dns name

**Comment by nutrina** [comment]
Open points:
- apps running on xyz domain should use band running on xyz domain:
  - scorer
  - passport
  - staking
