### ISSUE TITLE
Pull active DIDs & Stream IDs

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#2918]
Ceramic is looking to help migrate Passport from Kubo to Ceramic 1. If we can isolate just the last 90 day active DIDs & Stream IDs they could migrate just the users who have active stamps and reduce the time needed to migrate and get us running on Ceramic One

We just need to pull active users with score > 0 in the last 90 days:

- [ ] Eth Address (DID)
- [ ] Ceramic Stream ID

**Comment by nutrina** [comment]
I've done an export
But depending on when data will be migrated / backfilled it might be worth doing another one ...

**Comment by Jkd-eth** [comment]
@nutrina I'm going to move this to closed based on the last conversation that we had with Ceramic that they will not need an updated export to migrate to Ceramic 1
