### ISSUE TITLE
Optimize AWS Glue Job to Export Only New Data from DynamoDB to Redshift

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2927]
### User Story:
As a data engineer,
I want to adjust the AWS Glue script to export only the new data from DynamoDB to Redshift,
So that I can reduce the data size and time taken during each execution, making the process more efficient and cost-effective.

### Acceptance Criteria
GIVEN the AWS Glue script is scheduled to run,
WHEN the job executes,
THEN only the data that is new or updated since the last execution should be exported from DynamoDB to Redshift.

#### Product & Design Links:
<links>

#### Tech Details:

- Modify the existing AWS Glue script to include logic that identifies and exports only the new or updated records since the last execution.
- Implement a mechanism to track the timestamp of the last execution and compare it to the current data entries.
- Ensure that any potential edge cases (e.g., data updated multiple times or deleted entries) are handled gracefully.

#### Open Questions:

- [ ] What mechanism will be used to track the last execution timestamp? (e.g., storing in a metadata table?)
- [ ] How should we handle any potential data conflicts or failed exports?

#### Notes/Assumptions:

- The DynamoDB table contains a timestamp or versioning field that can be used to determine new or updated records.
- This will significantly reduce the data volume being exported and subsequently the loading times and resource consumption.
- Coordination with the team to ensure there's a clear understanding of any dependencies and to validate post-implementation behavior.
- Need to stop the job until the optimization is implemented and tested to avoid unnecessary resource usage.

**Comment by nutrina** [comment]
waiting for @NadjibBenlaldj  to confirm that this is a topic for engineering

**Comment by nutrina** [comment]
Ok, this is an engineering topic:

- double check that glue does indeed not allow incremental exports
- if not, then create dynamodb incremental exports to S3 in a daily schedule using https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/export_table_to_point_in_time.html#export-table-to-point-in-time
  - use `IncrementalExportSpecification` to specify a time window of 24h starting at midnight

**Comment by nutrina** [comment]
The monitoring of the lambda successful run sis still open.
