### ISSUE TITLE
Endpoint for Retrieving Model Scores

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2930]
### User Story:
As a developer,
I want an endpoint to retrieve model scores associated with a specified user,
So that I can get the necessary user data from the API.

### Acceptance Criteria
GIVEN a user address,
WHEN queried,
THEN the API should return model scores associated with that user.

#### Product & Design Links:
N/A
#### Tech Details:

- New endpoint `GET /v2/models/scores/{address}`.
- Endpoint should return the model scores associated with the specified user.

#### Open Questions:
N/A
#### Notes/Assumptions:

- Address of the user must be specified in the request.

**Comment by nutrina** [comment]
@lebraat @erichfi  for the model scores we have the analysis API.
I think this one should be for the "normal" score based on a users stamps. This should replace the `submit-passport` request I think ...

**Comment by lucianHymer** [comment]
We should create a new lambda for this endpoint as part of this ticket (to replace the /passport/analysis lambda)
