### ISSUE TITLE
Retire Submission Endpoint

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2933]
### User Story:
As a developer,
I want the submission endpoint to be retired,
So that I don't rely on deprecated or redundant functionalities.

### Acceptance Criteria
GIVEN the existing submission endpoint,
WHEN developers update to the new API version,
THEN the endpoint `POST /registry/submit-passport` should be retired.

GIVEN the `POST` endpoint got retired,
WHEN developers hit the `GET /v2/stamps/{scorer_id}/score/{address}` endpoint,
THEN the API should execute the same code which was used in the `POST` handler.

GIVEN the new `GET` endpoint succesfully executes a request
WHEN returning the payload
THEN it should have the following structure

```
{
    "address": "{address}",
    "score": [unique-humanity],
    "pass": true/false
    "last_score_timestamp": "{timestamp}",
    "expiration_date": "{expiration_date}",
"threshold": 20,
    "error": null,
    "stamp_scores": {
      "Ens": "2.2",
      "NFT": "0.69",
      "Google": "2.25"
      ...
    }
}
```

#### Product & Design Links:
N/A

#### Tech Details:

- Retire the endpoint `POST /registry/submit-passport` as it is no longer needed.
- Retire `/registry/score/{scorer_id}` for bulk score retrieval as well.

#### Open Questions:
N/A

#### Notes/Assumptions:
- Developers will be informed about the retirement of this endpoint and its alternatives.

**Comment by nutrina** [comment]
@erichfi  we should also retire:  `/registry/score/{scorer_id}` (bulk pull of scores)

**Comment by lucianHymer** [comment]
We should create a new lambda for this endpoint as part of this ticket (to replace the /registry/submit-passport lambda)
