### ISSUE TITLE
Fix the Shape mint button -- Stuck on Update after initial mint

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#2944]
### User Story:
As a user pushing onchain
I want to understand when I've minted, and not feel like I need to update my score
So that I can have piece of mind that my onchain attestation was minted properly

### Acceptance Criteria
GIVEN a user mints their passport onchain on Shape
WHEN the attestation is minted
THEN the button changes to Minted until my score changes.

1. When a user hasn't minted at all, the button says "Mint"
2. When the user mints, it will say "Minted" until the score changes
3. When the score changes, it will say "Update"

**Comment by Kweiss** [comment]
And to confirm, the button should be disabled if its in the 2nd state ("minted")
