### ISSUE TITLE
[BUG] Staked GTC not visible on Dashboard (Arbitrum)

### ISSUE THREAD

**Issue by YukiPL** [passportxyz/passport#2954]
**Overview**
User staked 125 GTC using Arbitrum, but the staked GTCs are not visible on the staking dashboard. User is also not able to verify the GTC Staking stamp.

User's wallet: 0x4b41CD1C80dB81C1CC923419b9C4d4cD4d13e9b5
Staking txid: https://arbiscan.io/tx/0x180cb12f894e8d8946040433aec593a8d4aa5ed671f148bd62fb03adfa1cdebd

**Expected behavior**
Staked GTC on Arbitrum should be showing on staking dashboard

**Screenshots**
![image](https://github.com/user-attachments/assets/e7729a94-64d2-477f-a1f2-1802c04cba37)

**Additional context**
User had tried using mobile and computer to connect on staking site, all give the same outcome.

**Comment by nutrina** [comment]
Have created a reindex request

**Comment by nutrina** [comment]
@YukiPL  the missing data was now indexed, the user should see his stake
