### ISSUE TITLE
GTC Staking Endpoint Retirement

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2957]
### User Story:
As a developer,
I want to mark the GTC Staking endpoint as deprecated in the documentation,
So that users are informed of its current operational status.

### Acceptance Criteria
GIVEN the GTC Staking endpoint,
WHEN developers view the documentation,
THEN it should be indicated as deprecated.

#### Product & Design Links:
N/A

#### Tech Details:
- Add a 'deprecated' label to the documentation regarding GTC Staking.

#### Open Questions:

- [ ] What additional information should be included about the endpoint's future?

#### Notes/Assumptions:
- The endpoint is not fully operational with Identity Staking V2.

**Comment by nutrina** [comment]
This refers to this endpoint: https://api.scorer.gitcoin.co/docs#/Passport%20API./registry_api_v1_get_gtc_stake_legacy

**Comment by lebraat** [comment]
@nutrina -- Please update the following language within the API Playground:

https://docs.google.com/document/d/17PgsRUAFkqV-RjVIkoIQBkDSvMQCNzfqDsEFq0BHvUY/edit?usp=sharing

@erichfi -- do we have another ticket in the backlog to create a new GTC Staking endpoint?
