### ISSUE TITLE
[BUG] Shape Onchain is not visible

### ISSUE THREAD

**Issue by YukiPL** [passportxyz/passport#2960]
**Overview**
The Shape Onchain option is not available/visible on the Passport's Dashboard.

**Steps To Reproduce**
1. Go to https://app.passport.xyz/#/dashboard
2. Click on Mint Onchain
3. See error

**Observed  behavior**
Onchain Shape option is not visible.

**Expected behavior**
Users should be able to see and select mint Passport on Shape

**Screenshots**
<img width="1297" alt="Screenshot 2024-10-09 at 11 13 16" src="https://github.com/user-attachments/assets/2492d80a-6347-400b-a8a2-e8b8888dc020">
<img width="1299" alt="Screenshot 2024-10-09 at 11 13 29" src="https://github.com/user-attachments/assets/196b5faa-edef-4e5b-8cee-549f378e5bf0">

**Additional context**
Browser used: Chrome

**Comment by lucianHymer** [comment]
Users can only mint on shape if they are on the shape custom dashboard https://app.passport.xyz/#/shape/

**Comment by kingbet1989** [comment]
Bih
