### ISSUE TITLE
Exploration of End-to-End Embeddable Widget for Passport Score

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2964]
### User Story:
As a technical team member exploring future embed work,
I want to create a basic embeddable widget that displays a Passport EVM Score,
So that I can understand the complexity and technical requirements of the embed functionality, ensuring compatibility with most Ethereum dApp web frameworks.

### Acceptance Criteria
GIVEN a basic widget that accepts a wallet address,
WHEN the wallet address is input,
THEN the widget should return and display the corresponding Passport's EVM Score,
AND it should be easily embeddable across different dApp sites.

#### Product & Design Links:
N/A - Focus is purely on functionality, not design.

#### Tech Details:
- Accept a wallet address as input.
- Query and display the Passport EVM Score.
- Ensure compatibility across major Ethereum dApp frameworks using a model similar to [Uniswap’s integration](https://docs.uniswap.org/contracts/v2/guides/interface-integration/iframe-integration).

#### Open Questions:

- [ ] What security measures are necessary for handling wallet addresses?

#### Notes/Assumptions:

- This feature is for technical exploration, not production use.
- Focus is on functionality; design details are secondary.
- The integration should prioritize ease of use and compatibility for partners.

**Comment by nutrina** [comment]
On the client side we'll need:
- Inputs:
  - API key
    - at some point we might want to think about restricting API key usage to certain domains
  - address
  - in the future we might also want to have providers (in case we will want to write info to the blockchain)
- we'll only perform `evm` checks
  - for this we should implement an API in the IAM, that performs the EVM stamp verifications without receiving any provider as imput
  - the `iam` will keep track of the current list of `evm` stamps, not the client as it is the case with the 1-click verification flow

**Comment by lucianHymer** [comment]
https://docs.google.com/document/d/1GXVTSNpxmVtCBEUV46Tn1Pv0ovP7O3gxg6m1GgIu7pU
