### ISSUE TITLE
Notify Developers of Score Changes Due to Deduplicated Stamps (API v2)

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#3003]
### User Story:
As a developer integrating Passport XYZ's Unique Humanity Score through API v2,
I want to be notified when a user's score is impacted by deduplication stamps,
So that I can maintain the accuracy and integrity of user interactions in my application, while protecting user privacy.

### Acceptance Criteria
GIVEN a developer is using the Passport XYZ API v2 to retrieve a user's Unique Humanity Score,
WHEN the score is affected by the deduplication of stamps or addresses,
THEN the "getScore" endpoint in API v2 should return additional information in the payload, indicating that a stamp/address has been deduplicated.

GIVEN the expiration date of the Passport Stamp in the Passport which gets the hash / stamp first accredited
WHEN the dedup note gets returned for the Passport which doesn't get the stamp accredited 
THEN we include the date for when the Stamp that currently is causing the deduplication expires

#### Product & Design Links:
N/A

#### Tech Details:

- Introduce a new field in the "getScore" response payload for API v2 to notify about deduplication effects, e.g., deduplicationEffect: true.
- This field should solely serve as an informational flag, without revealing any specific details about the linked addresses involved in the deduplication, ensuring privacy.
- Suggested payload structure:

```
{
	"address": "0xd8191177c9628f642d50be2349c8e70660a253dd",
	"score": "33.538",
	"passing_score": true,
	"last_score_timestamp": "2024-11-17T14:46:22.900951+00:00",
	"expiration_timestamp": "2025-02-06T14:28:06.879000+00:00",
	"threshold": "20",
	"error": null,
	"stamp_scores": {
		"Discord": {
                          "score": "0.516",
                          "dedup": true,
                          "expiration_date": "<date>"
                      
         }
}
```
Missed a curly in there, but you get what I mean

#### Open Questions:

- [ ] What guidance should be provided regarding how developers should utilize this deduplication information within their applications?

#### Notes/Assumptions:

- This feature is intended to ensure transparency wherein developers are informed of score changes due to deduplication, without compromising user privacy.
- The upgrade applies to our new API v2, ensuring developers are using the latest and most secure integrations.
- Documentation and developer support will be updated to reflect these enhancements and assure seamless adoption.

**Comment by lebraat** [comment]
Thanks for putting this together Erich!

-----

_What guidance should be provided regarding how developers should utilize this deduplication information within their applications?_

Developers can use this in a couple of different ways:
1. They can display a warning, such as the following:

> "Your score may differ from your score within the Passport XYZ app since you've claimed the [_stamp_] with another account. Learn more about this deduplication [_here_](_link to Passport support knowledge base article_)."

2. If a user complains about a difference in score between the Passport XYZ app and their scorer, it will be much easier for them to support themselves. I'll put together an FAQ that describes how to troubleshoot score differences like this. 

The below design might make #1 difficult for partners to be proactive about. 

-----

As far as a design, I wonder if we can do a couple of things...

First, I think we should add a single field within the credential object returned with `GET /v2/stamps/{address}`

```
			"credential": {
				"type": [	...  ],
				"proof": {  ...  },
				"issuer": "did:ethr:0xd6f8d6ca86aa01e551a311d670a0d1bd8577e5fb",
				"@context": [ ... ],
				"issuanceDate": "2024-11-17T14:44:32.751Z",
				"expirationDate": "2025-02-15T14:44:32.751Z",
				**"deduplicated": true / false**
				"credentialSubject": { ... }
			}
```

Second, could we add a value to the `GET /v2/stamps/{scorer_id}/scores/{address}` endpoint's `error` field that suggests when a deduplication happens?

Reason being, the vast majority of developers will only use this endpoint, so the `deduplicated` field within the `GET /v2/stamps/{address}` endpoint will not be that valuable unless developers are notified via the endpoint they are actually using. 

A potential value could be...

{
  ...
  "error": "This user has one or more Stamps that have been deduplicated. This means the score that returns with this endpoint will differ from the score within the Passport XYZ app. Please refer to the `deduplicated` field that returns in the `credentials` object from the `GET /v2/stamps/{address}` endpoint to identify which Stamps have been deduplicated. You can learn more about Stamp deduplication here: https://docs.passport.xyz/building-with-passport/major-concepts/deduplicating-stamps",
 ...
}

----- 

Thoughts?

**Comment by nutrina** [comment]
Suggested structure for score struct:

```json

{
  "address": "0x85ff01cff157199527528788ec4ea6336615c989",
  "score": "95.218",
  "passing_score": true,
  "last_score_timestamp": "2024-11-25T20:10:46.280869+00:00",
  "expiration_timestamp": "2024-11-27T14:32:37.411000+00:00",
  "threshold": "20",
  "error": null,
  "stamp_scores": {
    "Linkedin": "1.531",
    ...
  },
  // We would add the following attribute
  "deduplication": {
    "Linkedin": { ... }, // TODO: clarify the content of this 
    ...
  },
}

```

**Comment by lebraat** [comment]
Some questions:
* Would `deduplication` always deliver, regardless of whether there is a dedup or not? If it does always deliver, what would it look like if there weren't any deduplications?
* Simliar to `stamp_scores`, would it only return Stamp objects that have a deduplication?
* Since we are going to avoid including address in the response, would there be anything other than a true/false that would deliver in the `deduplication.{stamp}` object?
* Have you considered turning each field under `stamp_score` into an array that has a `score` and `dedup` fields? Still a little messy, but another option.
