### ISSUE TITLE
Update and Validate the Gitcoin Eligible Rounds Link for Improved User Accessibility and Accuracy

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#3013]
### User Story:
As a user of the Gitcoin platform,
I want the link to eligible rounds to be accurate and functional,
So that I can easily access up-to-date information without encountering errors.

### Acceptance Criteria
GIVEN the current link to Gitcoin's eligible rounds,
WHEN users attempt to access it,
THEN they should be directed to the new updated link: [Gitcoin Rounds CSV](https://github.com/ufkhan97/gitcoin-grants-heroku/blob/main/data/all_rounds.csv), and verify the eligibility of the rounds before the update is made.

#### Product & Design Links:
[New Target Link](https://github.com/ufkhan97/gitcoin-grants-heroku/blob/main/data/all_rounds.csv)

#### Tech Details:

- Update the existing hyperlink in the application's codebase to point to the new link.
- Check the eligibility status of rounds listed in the CSV.

**Comment by tim-schultz** [comment]
@erichfi this could cause confusion since https://github.com/ufkhan97/gitcoin-grants-heroku/blob/main/data/all_rounds.csv lists the ongoing rounds. User's won't be able to get a stamp for the current round until it is complete and we process the data.
