### ISSUE TITLE
[BUG] staking site not working for OP

### ISSUE THREAD

**Issue by YukiPL** [passportxyz/passport#3030]
**Overview**
User said when he switched to OP on staking site, it gives him this error. I have tried it on my end, but it works for me. 
He said it works fine with ETH chain. he tried clearing caches as well. 

**Steps To Reproduce**
1. Go to https://stake.passport.xyz/
2. Click on Connect Wallet
3. Switch to OP

**Observed  behavior**
![image](https://github.com/user-attachments/assets/1f6aee3f-924c-46f9-a647-b70158a28da1)
**waiting for user to get back on console log. 

**Expected behavior**
Should direct user to OP without throwing error.

**Additional info**
Please see video here: https://discord.com/channels/1201910237238399006/1278013086401429635/1303665710882361374

**Comment by nutrina** [comment]
Unable to reproduce the problem
waiting for more info from user

This worked for me with OKX on OP
