### ISSUE TITLE
Implement Revocation and Ban Lists for Sybil Detection

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#3051]
### User Story:
As a platform manager,
I want to revoke scores and credentials of users involved in Sybil Rings and ensure they are banned from claiming specific credentials and stamps,
so that I can maintain the integrity and security of Passport XYZ by preventing misuse and gaming of the system.

### Acceptance Criteria

GIVEN certain user addresses identified as part of Sybil Rings or engaging in suspicious activities,
WHEN I upload a CSV with the details of this addresses and their credentials in the django **revocation** list
THEN this respective credentials must be revoked
AND they should not be displayed any more in the Passport App <<<--- is this true? Or do we want to label them as `Revoked`
AND no points should be counted towards the score for these stamps

GIVEN certain user addresses identified as part of Sybil Rings or engaging in suspicious activities,
WHEN I upload a CSV with the details of this addresses and their credentials in the django **ban** list
THEN this respective addresses should not be allowed to verify the flagged credentials until the ban is lifted or expires
AND they when trying to verify a banned stamp, they should receive a correct error message highlighting the ban <<<--- is this correct?

#### Product & Design Links:
N/A

#### Tech Details:

- Develop and maintain a revocation list in line with VC specification variants, enabling credential revocation for detected Sybil behaviour
  - this for example is a specification for a revocation list https://www.w3.org/TR/vc-data-model-2.0/#status
- Implement a ban list mechanism preventing credential claims within defined timeframes (temporary and permanent).
- Ensure seamless integration with existing architecture, accommodating potential future on-chain revocation needs.
- Ban / Revocation Tiers:
  1. Temporarily ban a hash from the system
  2. Permanently ban a hash from the system
  3.  Temporarily ban a stamp of a user
  4.  Permanently ban a stamp of a user
  5. Temporarily ban an account of a user
  6. Permanently ban an account of a user
- Make the temporary ban duration times configurable
- DB Table
  1 What type of ban (stamp, hash, account)
  2 Identifier
  3 Time frame / duration   

#### Open Questions:

- [ ] How granular should the revocation and ban be? Is it at the individual credential or user account level?
- [ ] What are the potential impacts on scoring and legitimacy if on-chain credentials are not initially incorporated into this system?
- [ ] How will user disputes or appeals against revocation or banning be managed?

#### Notes/Assumptions:

- The default specification for revocation lists needs modification to include temporary locks.
- Initial implementation focuses on non-on-chain credentials; further investigation into on-chain revocation is desired for future iterations.

**Comment by nutrina** [comment]
@erichfi regarding the ban list, what exactly should we ban?
a. shall we ban an address from claiming a certain provider (like address A is not allow to claim Google)?
b. shall we ban a certain stamp hash from being claimed (i. e. we would ban a given ETH address or the Web3 stamps, and the account for the Web2 stamps)
c. or both options

**Comment by lebraat** [comment]
Stupid question: why would we ban just a Stamp when we can just label the entire account suspicious? 

Separately, +1 to having an appeal process.

**Comment by nutrina** [comment]
resuming work on this
