### ISSUE TITLE
Decommission Unused Subdomains

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#3084]
### User Story:
As a member of the Passport Engineering team, I want to decommission the unused subdomains review.passport.gitcoin.co and staging.passport.gitcoin.co, as well as remove the delegated hosted zone, so that we can improve security and prevent unauthorized access or misuse of these subdomains.

### Acceptance Criteria
GIVEN that the subdomains review.passport.gitcoin.co and staging.passport.gitcoin.co are no longer in use,
WHEN a team member initiates the decommissioning process,
THEN the subdomains should be taken down and any associated hosted zones should be removed.

- No redirects are needed for these subdomains.
- Verify there is no impact on other active services or subdomains.
- Confirm that removal of the hosted zone does not affect other necessary services.

#### Product & Design Links:
N/A

#### Tech Details:

- Identify all necessary steps to safely decommission the subdomains and remove the hosted zone.
- Ensure that any DNS changes comply with our standard procedures and do not inadvertently affect other services.
- Verify the removal process with logs or monitoring systems where applicable.
- Also remove the delegations in place around these domains.

#### Open Questions:
N/A

#### Notes/Assumptions:

- It is assumed that there is no legitimate traffic currently reliant on these subdomains.
- It is assumed that these subdomains do not need to be preserved for historical reference or backup purposes.

**Comment by larisa17** [comment]
`review.passport.gitcoin.co` & `staging.passport.gitcoin.co`:
- fleek app was deleted manually
- related DNS records from the main account (73.....42) was removed

**Comment by larisa17** [comment]
Additionally : 
- `passport.gitcoin.co` fleek app was removed (`oldpassport.gitcoin.co` record removed)
- `staging.passport-signer.gitcoin.co`  fleek app & records were removed 
- `billowing-cloud-5753` fleek app removed
- `passport-signer.gitcoin.co` fleek app & records were removed
