### ISSUE TITLE
[BUG] Multiple "Verification Failed" reports

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#3101]
**Overview**
A few users are reporting challenges with verifying different Stamps. They are claiming that they are receiving the following error message:

"Verification Failed: There was an issue verifying your Stamp"

**Steps To Reproduce**
1. Go to 'the app'
2. Click on 'Verify' for different Stamps
3. See error

**Observed  behavior**
There have been ____ users who have reported this:

0x1dd00e347b0ac89df5b51aa8955236142abc3bc9
Trying to receive BABT but failing. Confirmed that they have BABT in the proper address

0xB287f71Adf6Db85D8693D9f51171d214760f55ff
Had previously verified several Stamps but running into errors. Evidence of previous Stamp verification:
https://explorer.ver.ax/linea/attestations/0x00000000000000000000000000000000000000000000000000000000004b0c8a

**Expected behavior**
Able to work through flow and verify Stamps

**Comment by larisa17** [comment]
@lebraat  , me and @nutrina looked into this and there seems to not be any issues with the implementation: 
- @nutrina  was able to verify the Binance stamp 
- `0x1dd00e347b0ac89df5b51aa8955236142abc3bc9` seems to qualify for the Binance stamp .
Could you get in touch with the users and see if the issue persists ? if so, could you get more details about the errors : a screen shot of the pop-up with the error details would be helpful ?

**Comment by lebraat** [comment]
Still waiting for folks to respond with some additional details. I'll get back to you as soon as they do.

**Comment by Jkd-eth** [comment]
@lebraat Are you OK if we close this one out?

**Comment by lebraat** [comment]
Yep -- I'll reopen if I see other reports.
