### ISSUE TITLE
Sunset public.scorer.gitcoin.co

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#3106]
Waiting on confirmation from the Gitcoin Grants team, once we have verified we'll remove this domain.

Ideally we should do this in 2 steps:

1) prevent public access to bucket
2) if nobody complains in 1-2 weeks, nuke the bucket, domain, cloudfront, etc ...

**Comment by nutrina** [comment]
We should schedule this for the release on the 17th.
I have informed the Grants team that that is the date when we do it, unless they object.

**Comment by larisa17** [comment]
Step 1 is going to production today. 
We will wait a bit to see if anybody is effected and after that remove the public hosted zone, cronjobs, bucket & dns delegations
