### ISSUE TITLE
Pre-check to reduce Alchemy errors

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#3117]
Discord thread here: https://discord.com/channels/1201910237238399006/1218698890208088065/1314254371814506507

We're getting errors triggered from Alchemy when trying pull onchain Passport(s) if they have not minted a Passport onchain.

We should add back in a check for the attestation ID prior to hitting alchemy and reverting. (we can use the old code)

**Comment by lucianHymer** [comment]
https://github.com/passportxyz/passport/blob/28b746efcad89de2237a29faeea62c33b6ba4ef7/app/utils/onChainStamps.ts#L38

Old code: https://github.com/passportxyz/passport/blob/bb4cd1ff03a87beb6de2039f365002fb5948ec55/app/utils/onChainStamps.ts#L40

We should basically just check for the Passport attestation and make sure that the ID returned isn't 0, and then use the new method
