### ISSUE TITLE
[BUG] Coinbase Stamp triggering 403s when being verified

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#3119]
**Overview**
Many users are currently receiving 403 errors after they sign in with Coinbase as part of the Stamp verification process. 

These users seem to have properly verified the Coinbase ID within Coinbase, but the OAuth flow seems to be triggering errors. 

The specific error that they are receiving:
```[
  {
    "code": 403,
    "error": "Coinbase user id was not found."
  }
]```

And here is a list of the tickets that we've received related to this:
https://app.intercom.com/a/inbox/xaafeyri/inbox/search?filters=eyJwcmVkaWNhdGVzIjpbeyJpZGVudGlmaWVyIjoidGFncyIsInR5cGUiOiJhbmQiLCJwcmVkaWNhdGVzIjpbeyJhdHRyaWJ1dGUiOiJjb252ZXJzYXRpb24udGFnX2lkcyIsImNvbXBhcmlzb24iOiJpbiIsInR5cGUiOiJtYW51YWxfdGFnIiwidmFsdWUiOiIxMDMxNDM3OSJ9XX1dfQ%3D%3D&view=List


**Steps To Reproduce**
1. Go to 'the Passport app. Have the Coinbase SBT.'
2. Click on 'the Coinbase Stamp's "verify button"'
3. Login
4. See error

**Observed  behavior**
After logging in successfully, users are receiving the 403 error within the Passport app.

**Expected behavior**
The users should see that the Coinbase Stamp was successfully verified, without any errors throwing

**Comment by lebraat** [comment]
This is also affecting US users. This is my account:
<img width="1095" alt="Screenshot 2024-12-09 at 1 08 23 PM" src="https://github.com/user-attachments/assets/efd92d99-0c13-41ab-9b66-db682f8e4ade">

**Comment by Jkd-eth** [comment]
It's impacting both US and Int'l accounts and it's easy to repro in the US if you want @lebraat or myself to help pair on it
